title: CodeBangladesh.org
description: >-
  সফটওয়্যার ডেভেলপমেন্ট, প্রোগ্রামিং ও টেক জব সংক্রান্ত ফ্রি কনটেন্টগুলো একসাথে সাজিয়ে উপস্থাপন করা যাতে
  যারা নতুন শিখছেন তারা দ্রুত ভালভাবে শিখতে পারেন।
author: CodeBangladesh.org
email: admin@codebangladesh.org

baseurl: ""
url: "https://CodeBangladesh.org"

github_username:  CodeBangladesh-org
google_analytics: UA-195294918-1

exclude:
  - generated

# Custom Properties
header_text: বাংলায় শিখি সবকিছু
discord_invite: https://discord.gg/RsCDspZKqM
github_link: https://github.com/CodeBangladesh-org
android_appstore_link: https://play.google.com/store/apps/details?id=org.codebangladesh

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

minima:
  timezone: Europe/Amsterdam

collections:
  articles:
    output: true