id: application-security-and-ethical-hacking
name: আপ্লিকেশন সিকিউরিটি ও ইথিক্যাল হ্যাকিং
image_source: /assets/img/hacker.png
number_of_courses: dynamic
number_of_videos: dynamic
number_of_topics: dynamic